# Generated by Django 5.2.7 on 2025-11-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.IntegerField(default=1),
        ),
    ]
